version: '3'

services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./dinner_time/media:/app/dinner_time/media
    depends_on:
      - server

  db:
    container_name: database
    restart: always
    image: postgres:11.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  server:
    container_name: api_server
    restart: always
    build: .
    env_file:
      - $ENV
    expose:
      - 8000
    volumes:
      - ./dinner_time/media:/app/dinner_time/media
    command: scripts/docker-entrypoint.sh
    depends_on:
      - db

  backups:
    container_name: backup
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./backup:/backups
    links:
      - db:db
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@weekly
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=80

volumes:
  postgres_data: